
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep 30 2019 12:32:10 IST (Sep 30 2019 07:02:10 UTC)

// Verification Directory fv/lookahead16bit 

module lookahead4bit(c_in, a, b, s, c_out);
  input c_in;
  input [3:0] a, b;
  output [3:0] s;
  output c_out;
  wire c_in;
  wire [3:0] a, b;
  wire [3:0] s;
  wire c_out;
  wire n_0, n_1, n_2, n_3, n_5, n_6, n_8, n_9;
  wire n_11, n_12;
  OAI21XL g204(.A0 (n_11), .A1 (n_3), .B0 (n_12), .Y (s[3]));
  NAND2XL g205(.A (n_3), .B (n_11), .Y (n_12));
  AOI22XL g206(.A0 (n_9), .A1 (n_1), .B0 (a[2]), .B1 (b[2]), .Y (n_11));
  MXI2XL g207(.A (n_8), .B (n_9), .S0 (n_1), .Y (s[2]));
  CLKINVX1 g208(.A (n_8), .Y (n_9));
  AOI22XL g209(.A0 (n_6), .A1 (n_2), .B0 (a[1]), .B1 (b[1]), .Y (n_8));
  MXI2XL g210(.A (n_5), .B (n_6), .S0 (n_2), .Y (s[1]));
  CLKINVX1 g211(.A (n_5), .Y (n_6));
  AOI22XL g212(.A0 (n_0), .A1 (c_in), .B0 (a[0]), .B1 (b[0]), .Y (n_5));
  CLKXOR2X1 g213(.A (c_in), .B (n_0), .Y (s[0]));
  CLKXOR2X1 g214(.A (b[3]), .B (a[3]), .Y (n_3));
  CLKXOR2X1 g215(.A (b[1]), .B (a[1]), .Y (n_2));
  CLKXOR2X1 g216(.A (b[2]), .B (a[2]), .Y (n_1));
  CLKXOR2X1 g217(.A (b[0]), .B (a[0]), .Y (n_0));
endmodule

module lookahead4bit_1(c_in, a, b, s, c_out);
  input c_in;
  input [3:0] a, b;
  output [3:0] s;
  output c_out;
  wire c_in;
  wire [3:0] a, b;
  wire [3:0] s;
  wire c_out;
  wire n_0, n_1, n_2, n_3, n_5, n_6, n_8, n_9;
  wire n_11, n_12;
  OAI21XL g204(.A0 (n_11), .A1 (n_3), .B0 (n_12), .Y (s[3]));
  NAND2XL g205(.A (n_3), .B (n_11), .Y (n_12));
  AOI22XL g206(.A0 (n_9), .A1 (n_1), .B0 (a[2]), .B1 (b[2]), .Y (n_11));
  MXI2XL g207(.A (n_8), .B (n_9), .S0 (n_1), .Y (s[2]));
  CLKINVX1 g208(.A (n_8), .Y (n_9));
  AOI22XL g209(.A0 (n_6), .A1 (n_2), .B0 (a[1]), .B1 (b[1]), .Y (n_8));
  MXI2XL g210(.A (n_5), .B (n_6), .S0 (n_2), .Y (s[1]));
  CLKINVX1 g211(.A (n_5), .Y (n_6));
  AOI22XL g212(.A0 (c_in), .A1 (n_0), .B0 (a[0]), .B1 (b[0]), .Y (n_5));
  CLKXOR2X1 g213(.A (n_0), .B (c_in), .Y (s[0]));
  CLKXOR2X1 g214(.A (b[3]), .B (a[3]), .Y (n_3));
  CLKXOR2X1 g215(.A (b[1]), .B (a[1]), .Y (n_2));
  CLKXOR2X1 g216(.A (b[2]), .B (a[2]), .Y (n_1));
  CLKXOR2X1 g217(.A (b[0]), .B (a[0]), .Y (n_0));
endmodule

module lookahead4bit_2(c_in, a, b, s, c_out);
  input c_in;
  input [3:0] a, b;
  output [3:0] s;
  output c_out;
  wire c_in;
  wire [3:0] a, b;
  wire [3:0] s;
  wire c_out;
  wire n_0, n_1, n_2, n_3, n_5, n_6, n_8, n_9;
  wire n_11, n_12;
  OAI21XL g204(.A0 (n_11), .A1 (n_3), .B0 (n_12), .Y (s[3]));
  NAND2XL g205(.A (n_3), .B (n_11), .Y (n_12));
  AOI22XL g206(.A0 (n_9), .A1 (n_1), .B0 (a[2]), .B1 (b[2]), .Y (n_11));
  MXI2XL g207(.A (n_8), .B (n_9), .S0 (n_1), .Y (s[2]));
  CLKINVX1 g208(.A (n_8), .Y (n_9));
  AOI22XL g209(.A0 (n_6), .A1 (n_2), .B0 (a[1]), .B1 (b[1]), .Y (n_8));
  MXI2XL g210(.A (n_5), .B (n_6), .S0 (n_2), .Y (s[1]));
  CLKINVX1 g211(.A (n_5), .Y (n_6));
  AOI22XL g212(.A0 (c_in), .A1 (n_0), .B0 (a[0]), .B1 (b[0]), .Y (n_5));
  CLKXOR2X1 g213(.A (n_0), .B (c_in), .Y (s[0]));
  CLKXOR2X1 g214(.A (b[3]), .B (a[3]), .Y (n_3));
  CLKXOR2X1 g215(.A (b[1]), .B (a[1]), .Y (n_2));
  CLKXOR2X1 g216(.A (b[2]), .B (a[2]), .Y (n_1));
  CLKXOR2X1 g217(.A (b[0]), .B (a[0]), .Y (n_0));
endmodule

module lookahead4bit_3(c_in, a, b, s, c_out);
  input c_in;
  input [3:0] a, b;
  output [3:0] s;
  output c_out;
  wire c_in;
  wire [3:0] a, b;
  wire [3:0] s;
  wire c_out;
  wire n_0, n_1, n_2, n_3, n_5, n_6, n_8, n_9;
  wire n_11, n_12;
  OAI21XL g204(.A0 (n_11), .A1 (n_3), .B0 (n_12), .Y (s[3]));
  NAND2XL g205(.A (n_3), .B (n_11), .Y (n_12));
  AOI22XL g206(.A0 (n_9), .A1 (n_1), .B0 (a[2]), .B1 (b[2]), .Y (n_11));
  MXI2XL g207(.A (n_8), .B (n_9), .S0 (n_1), .Y (s[2]));
  CLKINVX1 g208(.A (n_8), .Y (n_9));
  AOI22XL g209(.A0 (n_6), .A1 (n_2), .B0 (a[1]), .B1 (b[1]), .Y (n_8));
  MXI2XL g210(.A (n_5), .B (n_6), .S0 (n_2), .Y (s[1]));
  CLKINVX1 g211(.A (n_5), .Y (n_6));
  AOI22XL g212(.A0 (c_in), .A1 (n_0), .B0 (a[0]), .B1 (b[0]), .Y (n_5));
  CLKXOR2X1 g213(.A (n_0), .B (c_in), .Y (s[0]));
  CLKXOR2X1 g214(.A (b[3]), .B (a[3]), .Y (n_3));
  CLKXOR2X1 g215(.A (b[1]), .B (a[1]), .Y (n_2));
  CLKXOR2X1 g216(.A (b[2]), .B (a[2]), .Y (n_1));
  CLKXOR2X1 g217(.A (b[0]), .B (a[0]), .Y (n_0));
endmodule

module lookahead16bit(c_in, a, b, c_out, s);
  input c_in;
  input [15:0] a, b;
  output c_out;
  output [15:0] s;
  wire c_in;
  wire [15:0] a, b;
  wire c_out;
  wire [15:0] s;
  wire C4, C8, C12, c_4, c_8, c_12, c_16, n_0;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33;
  lookahead4bit A1(c_in, a[3:0], b[3:0], s[3:0], c_4);
  lookahead4bit_1 A2(C4, a[7:4], b[7:4], s[7:4], c_8);
  lookahead4bit_2 A3(C8, a[11:8], b[11:8], s[11:8], c_12);
  lookahead4bit_3 A4(C12, a[15:12], b[15:12], s[15:12], c_16);
  AO22X1 g1247(.A0 (b[15]), .A1 (n_32), .B0 (a[15]), .B1 (n_33), .Y
       (c_out));
  NAND2XL g1248(.A (n_7), .B (n_31), .Y (n_33));
  NAND3BXL g1249(.AN (a[15]), .B (n_7), .C (n_31), .Y (n_32));
  AOI21XL g1250(.A0 (b[14]), .A1 (a[14]), .B0 (n_30), .Y (n_31));
  AOI211XL g1251(.A0 (n_29), .A1 (n_3), .B0 (n_4), .C0 (n_2), .Y
       (n_30));
  OAI21XL g1252(.A0 (a[12]), .A1 (b[12]), .B0 (C12), .Y (n_29));
  OAI2BB1XL g1253(.A0N (a[11]), .A1N (n_27), .B0 (n_28), .Y (C12));
  OAI21XL g1254(.A0 (n_27), .A1 (a[11]), .B0 (b[11]), .Y (n_28));
  OAI2BB1XL g1255(.A0N (b[10]), .A1N (n_25), .B0 (n_26), .Y (n_27));
  OAI21XL g1256(.A0 (n_25), .A1 (b[10]), .B0 (a[10]), .Y (n_26));
  OAI2BB1XL g1257(.A0N (a[9]), .A1N (n_23), .B0 (n_24), .Y (n_25));
  OAI21XL g1258(.A0 (n_23), .A1 (a[9]), .B0 (b[9]), .Y (n_24));
  OAI2BB1XL g1259(.A0N (a[8]), .A1N (C8), .B0 (n_22), .Y (n_23));
  OAI21XL g1260(.A0 (C8), .A1 (a[8]), .B0 (b[8]), .Y (n_22));
  OAI2BB1XL g1261(.A0N (a[7]), .A1N (n_20), .B0 (n_21), .Y (C8));
  OAI21XL g1262(.A0 (n_20), .A1 (a[7]), .B0 (b[7]), .Y (n_21));
  OAI2BB1XL g1263(.A0N (a[6]), .A1N (n_18), .B0 (n_19), .Y (n_20));
  OAI21XL g1264(.A0 (n_18), .A1 (a[6]), .B0 (b[6]), .Y (n_19));
  OAI2BB1XL g1265(.A0N (a[5]), .A1N (n_16), .B0 (n_17), .Y (n_18));
  OAI21XL g1266(.A0 (n_16), .A1 (a[5]), .B0 (b[5]), .Y (n_17));
  OAI2BB1XL g1267(.A0N (b[4]), .A1N (n_14), .B0 (n_15), .Y (n_16));
  OAI21XL g1268(.A0 (n_14), .A1 (b[4]), .B0 (a[4]), .Y (n_15));
  OAI21XL g1269(.A0 (n_12), .A1 (n_0), .B0 (n_13), .Y (C4));
  OAI21XL g1270(.A0 (n_9), .A1 (n_0), .B0 (n_13), .Y (n_14));
  AOI21XL g1271(.A0 (b[3]), .A1 (a[3]), .B0 (n_11), .Y (n_13));
  AOI32XL g1272(.A0 (n_6), .A1 (a[0]), .A2 (b[0]), .B0 (n_10), .B1
       (c_in), .Y (n_12));
  NOR2XL g1273(.A (n_0), .B (n_8), .Y (n_11));
  CLKINVX1 g1274(.A (n_9), .Y (n_10));
  OAI21XL g1275(.A0 (a[0]), .A1 (b[0]), .B0 (n_6), .Y (n_9));
  AOI22XL g1276(.A0 (n_5), .A1 (a[1]), .B0 (a[2]), .B1 (b[2]), .Y
       (n_8));
  NAND3BXL g1277(.AN (n_2), .B (a[13]), .C (b[13]), .Y (n_7));
  AO21X1 g1278(.A0 (a[1]), .A1 (n_1), .B0 (n_5), .Y (n_6));
  AND2X1 g1279(.A (b[1]), .B (n_1), .Y (n_5));
  NOR2XL g1280(.A (b[13]), .B (a[13]), .Y (n_4));
  NAND2XL g1281(.A (b[12]), .B (a[12]), .Y (n_3));
  NOR2XL g1282(.A (b[14]), .B (a[14]), .Y (n_2));
  OR2X1 g1283(.A (b[2]), .B (a[2]), .Y (n_1));
  NOR2XL g1284(.A (b[3]), .B (a[3]), .Y (n_0));
endmodule

