/*
###############################################################
#  Generated by:      Cadence Innovus 16.21-s078_1
#  OS:                Linux x86_64(Host ID client02)
#  Generated on:      Mon Sep 30 15:37:28 2019
#  Design:            fulladder1bit
#  Command:           saveNetlist fulladder1bit-innovus-netlist.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep 29 2019 22:07:22 IST (Sep 29 2019 16:37:22 UTC)
// Verification Directory fv/fulladder1bit 
module fulladder1bit (
	C0, 
	A, 
	B, 
	S, 
	C1);
   input C0;
   input A;
   input B;
   output S;
   output C1;

   ADDFX1 g2 (.A(C0),
	.B(B),
	.CI(A),
	.CO(C1),
	.S(S));
endmodule

